# This code was generated by Brave's AI when asked how to solve
# the problem of jumping to the Transaction View of an account
# within the moneydance UI

from com.moneydance.apps.md.view.gui import MoneydanceGUI
from com.moneydance.apps.md.controller import Main

# Get the GUI object
mdGUI = MoneydanceGUI.getInstance() # Or via cast: (MoneydanceGUI)((Main)context).getUI()

# Retrieve the account object
account = mdGUI.getCurrentAccountBook().getRootAccount().getAccountByName("Checking")

# Show the account window (specific method depends on API version)
# Often involves passing the account to a view manager
mdGUI.showAccountTransactionView(account)    